USE RATING;
DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(256) NOT NULL,
    category ENUM ('CLIENT', 'DELIVERER', 'ADMIN', 'RESTAURANT') NOT NULL
) ENGINE=INNODB;

INSERT INTO USERS (name, password, category)
VALUES ('name1', '$2b$10$9.sY6LVjcIS4sVJXF.q46eDRLrLkqyPjioHbWnpUmMdwqlf6zCjj.', 'CLIENT'),
       ('name2', '$2b$10$WXMbJJCwIjjIILfMSgtlHOzL7nmVoJwtEp1qWTMBp9XTzGaJHBOz2', 'ADMIN'),
       ('name3', '$2b$10$YmmzyYLtLT3QC5fm9I/sXOJegc4g7CxtsFNJlJ.1BnmRh0ZFENet2', 'DELIVERER'),
       ('name4', '$2b$10$LF3BeVmhp8E2OCvwARSZMuJNNUq7cEpVVHEj87sLEdJk0uuAiD1CK', 'RESTAURANT');